### ISSUE TITLE
Not an issue, only a wondering ...

### ISSUE THREAD

**Issue by zymase** [imDema/FreeMove#1]
Hi,

I read an article about FreeMove on gHacks. FreeMove is going to come in really handy.

I am wondering about two things, related I guess to directory junctions.

1- How to proceed to revert a moved directory back to its original location (to remove the junction in fact)?
2- When uninstalling a program which has had any of its folders moved, any issues? Should I remove the junction first (as within point (1) above)?

Thanks for your help.

**Comment by imDema** [comment]
1. You only need to delete the junction and move the directory back to its place
2. To uninstall you a program you should proceed as you would do normally without deleting the junction. This way the uninstaller will delete all the files It needs to (even if they are in the new location) and leave the junction file and an empty directory where you moved the program which you can choose to delete manually or not (they take up almost no space)
