### ISSUE TITLE
How to Undo a move?

### ISSUE THREAD

**Issue by alcidowander** [imDema/FreeMove#11]
I just tried the program and moved my email client Mozilla Thunderbird from C: to D:.
The FreeMove program did it fine. However, Thunderbird does not find its configurations and saved messages anymore. So I prefer to undo this move. How to bring the move back again to the original directory, since the original directory on drive C now appears a shortcut only?
Thanks.

**Comment by imDema** [comment]
It's in the last part of the readme

> Delete the junction in the old location (this won't delete the content) and move the directory back to its original position

That said, would you mind giving me some more details about how you encountered the problem and how to recreate it? Since I've never had that happen with the programs I've tested
