### ISSUE TITLE
Is a new version planned?

### ISSUE THREAD

**Issue by SOSPCChrist** [imDema/FreeMove#15]
I find your program very interesting but there have been no updates since January 2020, have you stopped development?

Thanks,

Christophe

**Comment by SamueleLorefice** [comment]
I think the Dev is currently busy with other things as of his response on #8, he's open for pull requests tho.

**Comment by SOSPCChrist** [comment]
Hello,

thank you for your answer, don't hesitate to contact me again if there was
any change.


Christophe
https://sospc.name
https://forumsospc.fr
https://sospcchristophe.fr
