### ISSUE TITLE
CRASH: FreeMove errors & freezes moving C:/ProgramData folder on Win 10

### ISSUE THREAD

**Issue by evano** [imDema/FreeMove#2]
1. Start FreeMove Task: __Source _(C:/ProgramData)___ =>Target ___(E:/)___
1. FreeMove proceeds, copying files to target
1. FreeMove error message, __Can't move folder C:/ProgramData/Application Data/. Continue or Cancel?__
1. Choose __Continue__
1. Moving files progress animation continues, but no files are moved
1. Kill FreeMove.exe process with TaskManager

I didn't get to copy the debug contents in the FreeMove error message. If it helps, I've attached the 3 messages from the Windows Event Viewer.

The folder FreeMove choked on is a hidden folder called _Application Data_. It is a junction already and its target is _C:/ProgramData_. I don't know what its purpose is in that folder; it may be new to Win 10. But, if FreeMove tried to move its contents, it would lead to an infinite recursive loop.

I have a couple of suggestions that might help:

1. FreeMove could identify any junctions it encounters and copy without expanding them.
1. FreeMove could create individual junctions for each folder in the parent folder, instead of creating 1 junction for the parent folder
1. FreeMove could offer the user a more fine-grained file selection interface, thereby allowing the move of a parent folder with many sub-folders without having to run a FreeMove job on each sub-folder.

[FreeMove-WinApplicationLogs-20170429.xml.txt](https://github.com/imDema/FreeMove/files/966295/FreeMove-WinApplicationLogs-20170429.xml.txt)

**Comment by imDema** [comment]
Fixed by adding C:\ProgramData to a blacklist in commit https://github.com/imDema/FreeMove/commit/a62b68985c9bb724883bbe9f8c32a9e1901acdcf
