### ISSUE TITLE
Cancel Button

### ISSUE THREAD

**Issue by SamueleLorefice** [imDema/FreeMove#7]
A Cancel button would be appreciated (maybe i'll do a pull request later), found myself starting a copy and figuring out I was copying files in the wrong folder and there is not way to stop the process. Had to wait until it finishes and then move files back and re-run the program.

**Comment by imDema** [comment]
You are absolutely right, I'm surprised I hadn't thought about adding such a necessary feature.
A PR would be welcome, otherwise I'll add it when I can find the time to do so.

Thank you for the feedback

**Comment by imDema** [comment]
Added in 2.0.0 8c69da7
