### ISSUE TITLE
Please add single file mklink support

### ISSUE THREAD

**Issue by TigerCubDen** [imDema/FreeMove#9]
This soltware is very handy and useful! But sometimes I just want to move single file instead of a folder. In this situation I have to open cmd.exe and type mklink commands even though it's inconvenient.

**Comment by imDema** [comment]
To create a link to a single file you can use the shorcut creation built in Windows and achieve the same result, for this reason I don't think it would be a useful addition to the program.
If you have some use case which is not covered by the Windows shortcut creation, let me know and I may consider adding it.
